[package]
name = "wifi-android-connect-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
adb_client = "1.0.4"
log = "0.4.22"
mdns-sd = "0.11.3"
qrcode = { version = "0.14.1", default-features = false }
rand = "0.8.5"
zeroconf = "0.15.0"
